version: '3'
services:
  pgdatabase:
    image: postgres:14
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb
    volumes:
      - "./mydb:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.jp
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "9999:80"
